var enemyHeros = [
    {
        name: '关平',
        blood: 10,
        attackMin: 5,
        attackMax: 10,
        attackSkill: 3,
        defenceMin: 1,
        defenceMax: 10,
        agile: 15,
        scale: 0.28,
        positionX: 355,
        positionY: 200,
        blood_positionX: 100,
        blood_positionY: 470,
        blood_scaleX: 1.8,
        blood_scaleY: 1,
        animation: 'j_guanping',
        attackDistance: 90,
        moveDuration: 0.5
    },
    {
        name: '黄忠',
        blood: 15,
        attackMin: 5,
        attackMax: 8,
        attackSkill: 3,
        defenceMin: 1,
        defenceMax: 6,
        agile: 10,
        scale: 0.55,
        positionX: 435,
        positionY: 325,
        blood_positionX: 30,
        blood_positionY: 220,
        blood_scaleX: 1,
        blood_scaleY: 0.6,
        animation: 'j_huangzhong',
        attackDistance: 180,
        moveDuration: 0.5
    },
    {
        name: '黄忠',
        blood: 15,
        attackMin: 5,
        attackMax: 8,
        attackSkill: 3,
        defenceMin: 1,
        defenceMax: 6,
        agile: 10,
        scale: 0.55,
        positionX: 515,
        positionY: 450,
        blood_positionX: 30,
        blood_positionY: 220,
        blood_scaleX: 1,
        blood_scaleY: 0.6,
        animation: 'j_huangzhong',
        attackDistance: 180,
        moveDuration: 0.5
    },
    {
        name: '黄忠',
        blood: 15,
        attackMin: 5,
        attackMax: 8,
        attackSkill: 3,
        defenceMin: 1,
        defenceMax: 6,
        agile: 10,
        scale: 0.55,
        positionX: 435,
        positionY: 575,
        blood_positionX: 30,
        blood_positionY: 220,
        blood_scaleX: 1,
        blood_scaleY: 0.6,
        animation: 'j_huangzhong',
        attackDistance: 180,
        moveDuration: 0.5
    },
    {
        name: '关平',
        blood: 10,
        attackMin: 5,
        attackMax: 10,
        attackSkill: 3,
        defenceMin: 1,
        defenceMax: 10,
        agile: 15,
        scale: 0.28,
        positionX: 355,
        positionY: 700,
        blood_positionX: 100,
        blood_positionY: 470,
        blood_scaleX: 1.8,
        blood_scaleY: 1,
        animation: 'j_guanping',
        attackDistance: 90,
        moveDuration: 0.5
    }
];
